### PR TITLE
sorry I made a small mistake I just fixed it

### PR DESCRIPTION
**Pull request by Jac-Zac**

### CODE REVIEW

**Comment by rooklift** [comment]
Another thing - when you do `mv src Nibbler/` isn't that actually removing the src folder out of the repo?

**Comment by Jac-Zac** [comment]
> > Another thing - when you do `mv src Nibbler/` isn't that actually removing the src folder out of the repo?
> 
> I actually does but it is intentional since the npm command craete copies of it

Therefore there still end up beeing a src forder in the repo

**Comment by rooklift** [comment]
I mean it's unacceptable for the build script to be destroying the repo in this fashion, assuming I'm correct about what's happening.

But this is why I didn't want it here, it's too difficult for me to check its correctness without a Mac. I think you're going to have to publish what you like in your own repo, I'll link to it.

**Comment by rooklift** [comment]
(I deleted the script.)

**Pull request closed without merging**
