### PR TITLE
add app icon

### LINKED ISSUE #47: The app needs an icon
A dock is sad without it.

### PR DESCRIPTION
**Pull request by lealgo**
Only tested on Linux.
I'm not sure if icons are subject to copyright...
Tries to fix #47

### CODE REVIEW

**Comment by fohristiwhirl** [comment]
Huh, it's as simple as that, is it?

Still, in order to work for the prebuilt version, it will need to be:

`icon: path.join(__dirname, "nibbler.png"),`

And I can't really accept the likely-copyrighted icon...

**Comment by lealgo** [comment]
> Still, in order to work for the prebuilt version, it will need to be:
> `icon: path.join(__dirname, "nibbler.png"),`
This works for me. Thanks!

> And I can't really accept the likely-copyrighted icon...
Yeah I thought so, maybe start with a generic one?

**Comment by fohristiwhirl** [comment]
By the way, on Windows the Electron icon is used automatically - if that's not true on Linux I wonder if it's an Electron bug?

**Comment by lealgo** [comment]
> By the way, on Windows the Electron icon is used automatically - if that's not true on Linux I wonder if it's an Electron bug?

I don't know. If I open just electron it does show the electron icon. So maybe I'm doing it wrong in my Nibbler launcher?

**Comment by lealgo** [comment]
> By the way, on Windows the Electron icon is used automatically - if that's not true on Linux I wonder if it's an Electron bug?

I tried your Linux bundle (running the executable without a launcher) and it doesn't show an icon either.

**Comment by CiriousJoker** [comment]
Here's my take on an icon that's more generic: https://github.com/fohristiwhirl/nibbler/issues/47#issuecomment-657897858

**Comment by dav1312** [comment]
You also need to add the icon to the `useful_files` in the builder

**Comment by rooklift** [comment]
I guess the recently accepted install script for Linux has also solved the icon issue, more or less.

**Pull request closed without merging**
