### PR TITLE
Use regexp for tagline parsing

### PR DESCRIPTION
**Pull request by flori**
- This handles escaping of quotes and escaping backslashes in tag values.
- It also allows omitting the quotes in taglines, because some software
  emits such tags.
- Adds setup.pgn to test a board setup position with unquoted FEN value
  and escaped quotes and escape characters.

### CODE REVIEW

**Comment by rooklift** [comment]
I'm not really in favour of regex for this sort of thing. But I'll have a think about how the current situation can be improved.

I'm particularly worried about cases like this:

```
[White "White"]
[Black "Black"]
[Result "*"]

1. e4 c5 2. Nf3 d6 3. d4 cxd4 4. Nxd4 Nf6 5. Bc4 Nxe4 6. Qh5 e6 7. Bb5+ Nd7 {
[I think, though I am not quite certain, that comments like this can exist.]
} 8. Nxe6 Nf6 9. Bxd7+ Bxd7 10. Nxd8 Nxh5 11. Nxb7 Bc6 12. Na5 Bxg2 13. Rg1 Be4
14. Be3 Bxc2 15. Nc3 Be7 16. Rc1 Bg6 17. Nb5 *
```

Anyway I'll try and fix backslash-escaping and look into whether the " quotation marks are optional.

**Comment by flori** [comment]
According to https://en.wikipedia.org/wiki/Portable_Game_Notation
> PGN text begins with a set of "tag pairs" (a tag name and its value), followed by the "movetext" (chess moves with optional commentary).

So one can assume that tag pairs only appear at the beginning of a PGN file and a parser could only parse the tags until `^1. ` is encountered at the beginning of a line. After that only movetext is supposed to appear which can then be parsed accordingly.

**Comment by rooklift** [comment]
Thanks for nudging me about the issue. I've just now added code that handles escaped \\ and \" - so that just leaves the unquoted tags. I'll have a think about it. I'm also concerned about the possibilty of multigame PGN files that don't respect the requirement to have \n\n between games, though maybe that's paranoia. We don't deal with those correctly anyway...

**Comment by rooklift** [comment]
I think I've fixed the lack-of-quotation-marks case now. I just assume lines starting with [ can't be tags if the movetext has started, that'll be fine I guess. Can't do anything magical about broken files.

So I think that's all the desiderata achieved. Let me know if you find any files that don't open still.

**Comment by rooklift** [comment]
I'll merge the testcase in, if I can figure out how.

**Pull request merged**
