### PR TITLE
Improve piece dragging experience

### PR DESCRIPTION
**Pull request by silverslither**
Uses DataTransfer and CSS features to improve the user experience when dragging board pieces without performance hit, now more closely matching lichess and chess.com behavior

### CODE REVIEW

**Comment by rooklift** [comment]
The dragDiv is in the body at the bottom left, below most of the stuff, but this leads to strange results if the window is shrunk to the point where stuff overlaps with its location:

image

**Comment by silverslither** [comment]
added a quick hack which fixes it on my end

**Comment by rooklift** [comment]
One could even argue for 0% opacity? I think I prefer that personally, what do you think?

BTW could you make the changes use tabs instead of spaces? (Or I'll do it later if you prefer...)

**Comment by silverslither** [comment]
if i plan on contributing further or maintaining my own fork i might add a linter config, but for now ill just replace my edits
maybe the opacity can be a config option? im not sure how thats done because im not too familiar with electron (or maybe it doesnt need to be exposed in the menus at all since most people dont care)

**Comment by rooklift** [comment]
I decided to undo this - I'm not entirely sold on the aesthetics.

**Comment by silverslither** [comment]
im fine with that - it's your project after all.

**Pull request merged**
