### PR TITLE
Add Linux packaging resources

### LINKED ISSUE #172: Feature request: Add a default .desktop file
Make life easier for the Linux folks. Here's an example:
`nibbler.desktop`
```
[Desktop Entry]
Categories=Game;BoardGame
Comment=Nibbler is a real-time analysis GUI for Leela Chess Zero (Lc0).
Exec=/usr/bin/nibbler
GenericName=Chess Analysis GUI
Icon=nibbler
Name=Nibbler
Path=/usr/bin
Terminal=false
Type=Application
```

Maybe consider finally adding an icon too? I do like this suggestion: https://github.com/rooklift/nibbler/issues/47#issuecomment-657897858

### PR DESCRIPTION
**Pull request by cyqsimon**
Closes #172.

I was going through my old issues and saw this one, so I thought I'd finish it up.

I used the icon from https://github.com/rooklift/nibbler/issues/47#issuecomment-657897858. @ciriousjoker

Providing these files is sufficient on Linux; the rest (installing those files) is the packagers' job that we need not worry about. (FYI `.desktop` goes in `/usr/share/applications`; icon goes in `/usr/share/icons/hicolor/512x512/apps` or `/usr/share/pixmaps`.)

I'm not certain how to properly package icons on Windows though, sorry ¯\\\_(ツ)\_/¯. Maybe some changes need to be made in Electron's manifest or something. But at least having the files doesn't hurt.

### What it looks like on KDE

In the launcher:
shot-20221212-145707

Launched:
shot-20221212-145527

### CODE REVIEW

**Comment by cyqsimon** [comment]
I realised that we still need to update [builder.py](src/builder.py) and [install.sh](src/install.sh).

I am not that familiar with Python. @rooklift can you please help update builder.py to include these files? Then I can update install.sh depending on where you put them. Thanks.

**Comment by ciriousjoker** [comment]
Woohoo! One OS at a time guys! ;)

**Review by ciriousjoker — APPROVED** [review]
PR looks good to me (I'm not a maintainer though iirc).

Is it possible to use an svg icon or does that lead to incompatibilities with some DEs?

**Comment by rooklift** [comment]
If you just want these included in the repo for Linux users to copy, I guess that's fine. I suggest they go in `/src/res` rather than just `/res`.

**Comment by cyqsimon** [comment]
> Is it possible to use an svg icon or does that lead to incompatibilities with some DEs?

I think SVG icon support is mandated by FreeDesktop, so there shouldn't be any issues. I only used PNG because I didn't have a SVG =(. Can you post/link one?

**Comment by cyqsimon** [comment]
> I suggest they go in `/src/res` rather than just `/res`.

Okay, will do.

**Comment by rooklift** [comment]
Also `builder.py` is really just for my own use, I guess you don't need to worry about that.

**Comment by cyqsimon** [comment]
> Also `builder.py` is really just for my own use, I guess you don't need to worry about that.

Unfortunately it does matter if we use the current `install.sh`. What it does is that it grabs the release zip file, and extracts its contents. If I understand correctly, the release zips are generated by `builder.py`, so it would have to be updated to include `res/*`.

Alternatively I can rewrite `install.sh`, since I think it's pretty janky in its current state. Since the original author is here as well, I will open a new issue to discuss this with @ciriousjoker .

**Comment by ciriousjoker** [comment]
> > Is it possible to use an svg icon or does that lead to incompatibilities with some DEs?
> 
> I think SVG icon support is mandated by FreeDesktop, so there shouldn't be any issues. I only used PNG because I didn't have a SVG =(. Can you post/link one?

I was preparing the svgs, here are all the files I created:

[AppIcon_sources.zip](https://github.com/rooklift/nibbler/files/10208942/AppIcon_sources.zip)

I also created an updated version which I think looks much cleaner (warped glass + gradients) and cleaned up the Illustrator files.

Can you merge this separately?

**Comment by ciriousjoker** [comment]
@cyqsimon I'm not too familar with Freedesktop and I don't have a test environment right now to make sure the PR is working. I assume all I have to do is replace the `nibbler.png` with `nibbler.svg`? In that case sure I can create it.

**Comment by cyqsimon** [comment]
> I assume all I have to do is replace the `nibbler.png` with `nibbler.svg`?

Yep. I'll do the rest.

**Pull request merged**
