### PR TITLE
Replace Linux app icon with svg variant

### PR DESCRIPTION
**Pull request by ciriousjoker**
In 2020 I've designed an icon for Nibbler https://github.com/rooklift/nibbler/issues/47#issuecomment-657897858, which was never merged.

Now, this icon has been merged for Linux: https://github.com/rooklift/nibbler/pull/210

However, that PR was using the .png variant I provided in 2020. Freedesktop apparently mandates `.svg`, so I dug up the sources for the icon and exported it as `.svg`.

However, I also improved it a little (at least in my opinion), by adding a fisheye effect & a gradient to the magnifying glass.

Here are all the sources & exported svgs.
[AppIcon_sources.zip](https://github.com/rooklift/nibbler/files/10221242/AppIcon_sources.zip)

I think the updated one looks better, which is why I've used it in this PR, but let me know what you think.

---

Here's a comparison:

| original | updated |
|----------|-----------|
| AppIcon_original | AppIcon_updated |

### CODE REVIEW

**Comment by ciriousjoker** [comment]
@cyqsimon Your turn ;)

tyvm!

**Comment by rooklift** [comment]
Thanks, I'll leave this until we merge in the reorganisation of the files - which I think is waiting for an adjusted `install.sh` script - @cyqsimon do I have that right?

**Comment by cyqsimon** [comment]
> Freedesktop apparently mandates `.svg`

What I meant to say is that FreeDesktop mandates that `svg` be supported by desktop environments, alongside `png`. So technically, your old `png` icon works just fine =). But using vector graphics is certainly an improvement and more future-proof.

> which I think is waiting for an adjusted `install.sh` script

Correct, I'm working on that.

**Comment by cyqsimon** [comment]
@ciriousjoker can you please make this change on the `reorganise` branch instead? We are both working on that branch right now, and there's some major moving-files-around. Sorry for the trouble.

**Comment by cyqsimon** [comment]
> I can just update this PR once the other one is merged, do u agree?

Sure, although in that case you will have to modify a few lines in `builder.py` and `install.sh`. Shouldn't be too hard though.

Also I just started coughing really bad today, likely COVID. So you probably have to wait a few days, sorry.

**Comment by ciriousjoker** [comment]
Dw i'll just fast forward my branch. I've waited 2 years for this, a couple more days won't be an issue ;)

I wish you all the best and get well soon!

**Comment by cyqsimon** [comment]
@ciriousjoker reorganisation's done. Icon is now at `/files/res/nibbler.png`. Feel free to ask me if there's something you aren't sure about the scripts.

**Comment by ciriousjoker** [comment]
@cyqsimon

I pushed the icon files and added it to `builder.py`. Can you please check if `install.sh` needs to be changed as well? I didn't know what to do there.

Also, since you mentioned credits after my original comments, I've also included this line in the readme:

> Icon design by [ciriousjoker](https://github.com/ciriousjoker) based on [this](https://www.svgrepo.com/svg/155301/chess).

For windows users that line won't make much sense though. Do you know how to use that icon for Windows as well?

**Comment by cyqsimon** [comment]
> Can you please check if `install.sh` needs to be changed as well?

Yes. I'll submit a PR onto your branch.

> Do you know how to use that icon for Windows as well?

On Windows the icon is directly built into the exe as a resource. See `https://www.electronjs.org/docs/latest/tutorial/application-distribution#rebranding-with-downloaded-binaries`. I'm not confidently proficient in Python, so I'll leave this to @rooklift.

**Comment by ciriousjoker** [comment]
Now this should be ready to merge.

**Comment by rooklift** [comment]
Presumably I'll also have to remake `nibbler-2.3.9-linux.zip` so as to include the SVG file?

**Comment by cyqsimon** [comment]
> Presumably I'll also have to remake `nibbler-2.3.9-linux.zip` so as to include the SVG file?

That would be kind of messy, modifying a release retroactively. I think it would be best for the SVG files to simply be included in the next release.

Of course if you want to make a new release just for this that would be okay too.

**Comment by rooklift** [comment]
Is the install script happy enough for the svg file not to exist?

**Comment by cyqsimon** [comment]
> Is the install script happy enough for the svg file not to exist?

Nope, it will error, so it would be a good idea to rebuild the release. But retroactively editing the release is kind of messy, because there will be differences between the source archive at tag and the release `.zip`, and then the changed file hash may cause confusion downstream, etc.

It's probably the easiest to just make a new patch release, 2.3.10 or something.

**Pull request merged**
