### PR TITLE
I made the final changes

### PR DESCRIPTION
**Pull request by Jac-Zac**
Oh sorry I'didn't understood what you meant with the misc folder initially. I have fix it. Btw I have tested it on my m1 macbook and also another x86_64 mac that I have. Under different circumstances so I think it is quite safe to say that It works. Thought It would be great if other people who use mac test it on their machine to give me feedback if there is any problem.

### CODE REVIEW

**Comment by rooklift** [comment]
Thanks - shouldn't the final `mv` be `cp` ?

**Comment by Jac-Zac** [comment]
> Thanks - shouldn't the final `mv` be `cp` ?

I mean I doesn't really matter so it is up to you to decide what you prefer. You can go ahead and change it I don't mind at all

**Comment by rooklift** [comment]
Well, if it's `mv` isn't it effectively deleting it from the repo the first time you run the script?

**Comment by Jac-Zac** [comment]
Anyway I made the change and finished it so if you want you can merge it :-)

**Pull request merged**
